#!/bin/bash

BASE="/home/system/khronos.heatherly_cron_daemon"

function  my_mount {
   #---(name mountpoint)----------------------------#
   mpoint="${BASE}/${1}"
   #---(make mountpoint)----------------------------#
   mkdir "$1" 2> /dev/null
   rc="$?"
   printf "   %-10.10s  : " "${1}"
   if [ "${rc}" = "0" ];
      then  printf "made dir   , "
      else  printf "dir exists , "
   fi
   #---(umount)-------------------------------------#
   umount  "$mpoint" 2> /dev/null
   mount  --bind "/$1" "$mpoint" 2> /dev/null
   rc="$?"
   if [ "${rc}" = "0" ];
      then  printf "now mounted\n"
      else  printf "already mounted\n"
   fi
   #---(complete)-----------------------------------#
   return
}


function  my_umount {
   #---(name mountpoint)----------------------------#
   mpoint="${BASE}/${1}"
   #---(umount)-------------------------------------#
   umount  "$mpoint" 2> /dev/null
   rc="$?"
   printf "   %-10.10s  : " "${1}"
   if [ "${rc}" = "0" ];
      then  printf "now unmounted     , "
      else  printf "already unmounted , "
   fi
   #---(remove mountpoint)--------------------------#
   rmdir "$1" 2> /dev/null
   rc="$?"
   if [ "${rc}" = "0" ];
      then  printf "removed dir\n"
      else  printf "dir already removed\n"
   fi
   #---(complete)-----------------------------------#
   return
}


if [ "$1" = "mount" ]; then
   if [ ! -f "/khronos.c" ]; then
      printf "creating test environment...\n"
      my_mount  "bin"
      my_mount  "dev"
      my_mount  "etc"
      my_mount  "home"
      my_mount  "lib"
      my_mount  "lib64"
      my_mount  "opt"
      my_mount  "root"
      my_mount  "sbin"
      my_mount  "usr"
      chroot    "$BASE/" "/bin/bash"
   fi
else
   if [ ! -f "/khronos.c" ]; then
      printf "removing test environment...\n"
      my_umount "bin"
      my_umount "dev"
      my_umount "etc"
      my_umount "home"
      my_umount "lib"
      my_umount "lib64"
      my_umount "opt"
      my_umount "root"
      my_umount "sbin"
      my_umount "usr"
   fi
fi

